export default {
    dark: {
        bg: "#121212",
        surface: "#1E1E1E",
        primary: "#BB86FC",
        secondary: "#00DAC6",
        on_background: "",
        on_surface: "#E1E1E1",
        on_primary: "",
        on_secondary: "",
        text: "white",
    },
    light: {
        bg: "white",
        surface: "white",
        primary: "",
        secondary: "",
        on_background: "",
        on_surface: "",
        on_primary: "",
        on_secondary: "",
        text: "#121212",
    },
    accent: "#262A2C",
};
